# Generated by Django 6.0.2 on 2026-04-03 15:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_role', models.CharField(choices=[('STUDENT', 'Тест для ученика'), ('TEACHER', 'Тест для учителя')], max_length=20)),
                ('question_count', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тест определения уровня',
                'verbose_name_plural': 'Тесты определения уровня',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Супер-админ'), ('CENTER_ADMIN', 'Администрация центра'), ('TEACHER', 'Учитель'), ('STUDENT', 'Студент')], default='STUDENT', max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('phone_student', models.CharField(blank=True, max_length=32)),
                ('phone_parent', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('school_shift', models.CharField(blank=True, choices=[('MORNING', 'Утро'), ('AFTERNOON', 'День'), ('EVENING', 'Вечер')], max_length=20)),
                ('is_active_in_center', models.BooleanField(default=True)),
                ('joined_center_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.CharField(max_length=60)),
                ('course_duration_weeks', models.PositiveIntegerField(default=12)),
                ('cycle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='crm.subject')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['subject__name', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('homework', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='crm.studygroup')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='crm.studygroup')),
            ],
            options={
                'verbose_name': 'Расписание группы',
                'verbose_name_plural': 'Расписания групп',
                'ordering': ['group', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_start_number', models.PositiveIntegerField(default=1)),
                ('lesson_end_number', models.PositiveIntegerField(default=12)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='crm.studygroup')),
            ],
            options={
                'verbose_name': 'Платежный цикл',
                'verbose_name_plural': 'Платежные циклы',
                'ordering': ['-opened_at'],
                'unique_together': {('group', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=100)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('score_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('level', models.CharField(blank=True, choices=[('BEGINNER', 'Начальный'), ('BASIC', 'Базовый'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый')], max_length=20)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='crm.placementtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка тестирования',
                'verbose_name_plural': 'Попытки тестирования',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('exited_at', models.DateTimeField(auto_now_add=True)),
                ('removed_by', models.ForeignKey(limit_choices_to={'role__in': ['CENTER_ADMIN', 'SUPER_ADMIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='processed_exits', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выбытие пользователя',
                'verbose_name_plural': 'Выбытия пользователей',
                'ordering': ['-exited_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Присутствует'), ('ABSENT', 'Отсутствует'), ('LATE', 'Опоздал')], default='PRESENT', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('activity_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('homework_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('exam_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='crm.lesson')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Не оплачено'), ('PARTIAL', 'Частично оплачено'), ('PAID', 'Оплачено')], default='UNPAID', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.billingcycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-cycle__opened_at', 'student__last_name'],
                'unique_together': {('cycle', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='crm.studygroup')),
            ],
            options={
                'verbose_name': 'Зачисление в группу',
                'verbose_name_plural': 'Зачисления в группы',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group', 'student'), name='unique_active_enrollment')],
            },
        ),
    ]
