# Generated by Django 6.0.2 on 2026-04-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='placement_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Начальный'), ('BASIC', 'Базовый'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='placement_score_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
